id: P007852
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 12:45:02.635246
source_metadata:
  id: bdr:W8LS19153
  title: རྩོམ་གྱི་འབྲས་བུ་ཐོགས་པའི་མེ་ཏོག་ཚལ། སློབ་བུར་འཚམ་པའི་རྩོམ་དཔེ།
  author: ''
  volumes:
    102ab3a932f74495844e9d73ffa41e30:
      image_group_id: I8LS19155
      title: Volume 1 of rtsom gyi 'bras bu thogs pa'i me tog tshal/
      volume_number: 1
      total_pages: 132
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
