id: P007852
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19153
  title: རྩོམ་གྱི་འབྲས་བུ་ཐོགས་པའི་མེ་ཏོག་ཚལ། སློབ་བུར་འཚམ་པའི་རྩོམ་དཔེ།
  author: ''
  volumes:
    38f7beee07414af099a116b8b94d50cd:
      image_group_id: I8LS19155
      title: ''
      volume_number: 1
      total_pages: 132
ebook_metadata:
  title: རྩོམ་གྱི་འབྲས་བུ་ཐོགས་པའི་མེ་ཏོག་ཚལ། སློབ་བུར་འཚམ་པའི་རྩོམ་དཔེ།
  author: ''
  sku: P007852
  cover: cover.jpg
  layers:
  - pagination
